connector_image: airbyte/source-shopify:dev
tests:
  spec:
    - spec_path: "source_shopify/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "secrets/config.json"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      # Set to NO because some streams has 0 data on the source 
      validate_output_from_all_streams: no
  incremental: 
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      state_path: "integration_tests/abnormal_state.json"
      cursor_paths:
        charges: [ "id" ]
  full_refresh:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
